# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VC5cA1w3QEIETU5Oekltt4vn6fus-yRi
"""

import streamlit as st
import pandas as pd
import sqlite3

# Page Configuration
st.set_page_config(page_title="E-Commerce Analytics Dashboard", layout="wide")

st.title("🛒 E-Commerce Executive Analytics Case Study")
st.markdown("### Powered by Advanced SQL (CTEs, Window Functions & Cohorts)")
st.write("This interactive dashboard executes complex SQL queries live against a 11k+ order dataset.")

# Initialize SQLite Connection & Load Data in Memory
@st.cache_resource
def init_db():
    conn = sqlite3.connect(':memory:', check_same_thread=False)
    cursor = conn.cursor()

    # Read our SQL file generated previously
    # Make sure 'ecommerce_dataset.sql' is in the same folder
    with open('ecommerce_dataset.sql', 'r', encoding='utf-8') as f:
        sql_script = f.read()

    # SQLite compatibility adjustment (Remove MySQL specific commands if any)
    sql_script = sql_script.replace("CREATE DATABASE IF NOT EXISTS ecommerce_analytics;", "")
    sql_script = sql_script.replace("USE ecommerce_analytics;", "")

    cursor.executescript(sql_script)
    return conn

try:
    conn = init_db()
except Exception as e:
    st.error(f"Error loading database script: {e}")
    st.stop()

# Sidebar Navigation for business metrics
metric_choice = st.sidebar.selectbox(
    "Select Business Metric / Framework",
    ["Executive Summary", "RFM Customer Segmentation", "Cohort Retention Matrix", "Monthly Revenue Growth"]
)

# ---- DASHBOARD SECTIONS ----

if metric_choice == "Executive Summary":
    st.subheader("Business Health Check KPIs")

    # Query 1: Total Revenue
    rev_df = pd.read_sql_query("SELECT SUM(quantity * price_per_unit) as total_rev FROM order_items JOIN orders USING(order_id) WHERE status='Completed'", conn)
    # Query 2: Order Status
    status_df = pd.read_sql_query("SELECT status, COUNT(*) as count FROM orders GROUP BY status", conn)

    col1, col2 = st.columns(2)
    with col1:
        st.metric(label="Total Gross Revenue (Completed Orders)", value=f"${rev_df['total_rev'].iloc[0]:,.2f}")
    with col2:
        st.bar_chart(status_df.set_index('status'))

elif metric_choice == "RFM Customer Segmentation":
    st.subheader(" RFM (Recency, Frequency, Monetary) Analysis")
    st.markdown("Segments customers into tactical marketing tiers based on their past buying patterns.")

    rfm_query = """
    WITH rfm_raw AS (
        SELECT user_id,
               (JULIANDAY('2026-06-15') - JULIANDAY(MAX(order_date))) AS recency,
               COUNT(DISTINCT order_id) AS frequency,
               SUM(quantity * price_per_unit) AS monetary
        FROM orders JOIN order_items USING (order_id) WHERE status = 'Completed' GROUP BY user_id
    ),
    scores AS (
        SELECT *,
               NTILE(5) OVER (ORDER BY recency DESC) AS r_score,
               NTILE(5) OVER (ORDER BY frequency ASC) AS f_score,
               NTILE(5) OVER (ORDER BY monetary ASC) AS m_score
        FROM rfm_raw
    )
    SELECT user_id, recency, frequency, monetary,
    CASE
        WHEN r_score >= 4 AND f_score >= 4 AND m_score >= 4 THEN 'Champions / Loyal'
        WHEN r_score >= 3 AND f_score <= 2 THEN 'New / Promising'
        WHEN r_score <= 2 AND f_score >= 3 THEN 'At Risk / Retention Focus'
        WHEN r_score <= 1 THEN 'Lost / Dormant'
        ELSE 'Regular Customer'
    END AS customer_segment
    FROM scores;
    """
    df_rfm = pd.read_sql_query(rfm_query, conn)

    # Visualizing Segment Distribution
    segment_counts = df_rfm['customer_segment'].value_counts()
    st.bar_chart(segment_counts)
    st.dataframe(df_rfm.head(100))

elif metric_choice == "Cohort Retention Matrix":
    st.subheader(" Month-on-Month Customer Cohort Retention")
    st.markdown("Tracks user retention rates based on sign-up cohorts (SQL CTE processing).")

    # Simplified SQLite Cohort Query
    cohort_query = """
    WITH UserCohorts AS (
        SELECT user_id, STRFTIME('%Y-%m', created_at) AS cohort_month FROM users
    ),
    UserActivity AS (
        SELECT o.user_id, STRFTIME('%Y-%m', o.order_date) AS activity_month,
        ((STRFTIME('%Y', o.order_date) - STRFTIME('%Y', u.created_at)) * 12) +
        (STRFTIME('%m', o.order_date) - STRFTIME('%m', u.created_at)) AS month_number
        FROM orders o JOIN users u ON o.user_id = u.user_id WHERE o.status = 'Completed'
    ),
    CohortSizes AS (
        SELECT cohort_month, COUNT(DISTINCT user_id) AS total_users FROM UserCohorts GROUP BY cohort_month
    ),
    RetentionData AS (
        SELECT uc.cohort_month, ua.month_number, COUNT(DISTINCT ua.user_id) AS retained_users
        FROM UserCohorts uc JOIN UserActivity ua ON uc.user_id = ua.user_id WHERE ua.month_number >= 0
        GROUP BY uc.cohort_month, ua.month_number
    )
    SELECT r.cohort_month, s.total_users AS cohort_size,
           MAX(CASE WHEN r.month_number = 0 THEN ROUND(r.retained_users * 100.0 / s.total_users, 1) END) AS Month_0,
           MAX(CASE WHEN r.month_number = 1 THEN ROUND(r.retained_users * 100.0 / s.total_users, 1) END) AS Month_1,
           MAX(CASE WHEN r.month_number = 2 THEN ROUND(r.retained_users * 100.0 / s.total_users, 1) END) AS Month_2,
           MAX(CASE WHEN r.month_number = 3 THEN ROUND(r.retained_users * 100.0 / s.total_users, 1) END) AS Month_3
    FROM RetentionData r JOIN CohortSizes s ON r.cohort_month = s.cohort_month
    GROUP BY r.cohort_month ORDER BY r.cohort_month;
    """
    df_cohort = pd.read_sql_query(cohort_query, conn)
    st.dataframe(df_cohort)

elif metric_choice == "Monthly Revenue Growth":
    st.subheader(" Month-on-Month Revenue Trends")

    growth_query = """
    WITH MonthlyRev AS (
        SELECT STRFTIME('%Y-%m', order_date) AS order_month, SUM(quantity * price_per_unit) AS revenue
        FROM orders JOIN order_items USING(order_id) WHERE status = 'Completed' GROUP BY order_month
    )
    SELECT order_month, revenue,
           LAG(revenue) OVER (ORDER BY order_month) as prev_revenue
    FROM MonthlyRev;
    """
    df_growth = pd.read_sql_query(growth_query, conn)
    df_growth['growth_pct'] = ((df_growth['revenue'] - df_growth['prev_revenue']) / df_growth['prev_revenue']) * 100

    st.line_chart(df_growth.set_index('order_month')['revenue'])
    st.dataframe(df_growth)









